// This file was generated by prisma-field-encryption.

import type { PrismaClient, MessageEmbed } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = MessageEmbed['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'MessageEmbed',
    client,
    getTotalCount: client.messageEmbed.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.messageEmbed.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        title: true,
        description: true,
        url: true,
        authorName: true,
        authorUrl: true,
        authorIconUrl: true,
        footerText: true,
        footerIconUrl: true,
        thumbnailUrl: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.messageEmbed.update({
      where: {
        id: record.id
      },
      data: {
        title: record.title,
        description: record.description,
        url: record.url,
        authorName: record.authorName,
        authorUrl: record.authorUrl,
        authorIconUrl: record.authorIconUrl,
        footerText: record.footerText,
        footerIconUrl: record.footerIconUrl,
        thumbnailUrl: record.thumbnailUrl
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "title": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "description": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "url": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "authorName": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "authorUrl": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "authorIconUrl": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "footerText": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "footerIconUrl": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     },
 *     "thumbnailUrl": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "fields": {
 *       "modelName": "EmbedField",
 *       "isList": true
 *     },
 *     "message": {
 *       "modelName": "Message",
 *       "isList": false
 *     }
 *   }
 * }
 */
