name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Yarn
        run: yarn set version 3.2.1
      - name: Install modules
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn lint
      - name: Run Prettier
        run: yarn format:check
